### PR TITLE
Add instructions for Google Cloud Storage blobstore backing

### PR DESCRIPTION
**Pull request by zrob**
Please do not merge until @SocalNick has approved this.

### CODE REVIEW

**Comment by bentarnoff** [comment]
Thanks, @zrob! We'll block it on Nick's approval.

**Comment by jbheron** [comment]
@SocalNick bump for approval.

**Comment by SocalNick** [comment]
@jbheron this can be published with CF-242 which is about to be cut.

**Comment by jbheron** [comment]
Thanks, @SocalNick!

**Pull request merged**
