### PR TITLE
Document S3 Server Side Encryption

### PR DESCRIPTION
**Pull request by youreddy**
[#123901151]

### CODE REVIEW

**Comment by youreddy** [comment]
Hello docs team!

Please do not merge this in until Nick accepts this story: https://www.pivotaltracker.com/story/show/123901151

Thank you,
Urvashi

**Comment by bentarnoff** [comment]
Thanks, @youreddy ! We will block until Nick accepts that story.

**Comment by SocalNick** [comment]
Accepted

**Comment by bentarnoff** [comment]
Thanks, @youreddy and @SocalNick !

**Pull request merged**
