### PR TITLE
Document cc blobstore configuration for gcs with a service account

### PR DESCRIPTION
**Pull request by tylerschultz**
[#154187295]

Signed-off-by: Chris Selzo <cselzo@pivotal.io>

### CODE REVIEW

**Comment by selzoc** [comment]
Howdy docs team!  Please don't merge this until @zrob has a chance to review it and give it a 👍

**Comment by animatedmax** [comment]
Thank you @tylerschultz

**Comment by animatedmax** [comment]
Reverted with 6407486555745dcb7ab0d73a444aac061ec30337

**Comment by tcdowney** [comment]
Hi @animatedmax, we submitted a revised version of these docs here: https://github.com/cloudfoundry/docs-deploying-cf/pull/194

**Pull request merged**
