### PR TITLE
Add blobstore configuration docs

### PR DESCRIPTION
**Pull request by wendorf**
This is a small improvement over #99 to include a link to the documentation for setting up BOSH IAM instance profiles.

### CODE REVIEW

**Comment by bentarnoff** [comment]
Thanks, @wendorf. Waiting for acceptance of the Tracker story you referred to in #99. When that story is accepted, we will merge.

**Comment by SocalNick** [comment]
@bentarnoff this is ready to be merged

**Comment by bentarnoff** [comment]
Merged! Thanks, @SocalNick

**Comment by SocalNick** [comment]
Thanks @bentarnoff ! Do these get deployed via pipeline automatically or get pushed every so often?

**Comment by kimahoff** [comment]
@SocalNick the changes get deployed to our staging site automatically, but we push to prod by hand once or twice a week. I just published today, so the changes should be live now.

**Pull request merged**
