### PR TITLE
Changed CERTIFICATE to RSA PRIVATE KEY where applicable in examples i…

### PR DESCRIPTION
**Pull request by christianang**
Changed CERTIFICATE to RSA PRIVATE KEY in the consul security docs where applicable

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
@animatedmax thanks for merging #89.  This PR here is much older, wonder if it slipped through the cracks? /cc @kimahoff

**Comment by Amit-PivotalLabs** [comment]
Thanks!

**Comment by animatedmax** [comment]
Thank you, @christianang  

This PR was not initially merged because cfdreddbot didn't see a CLA for you, and we mistakenly overlooked your membership in the pivotal-cf org. Sorry for the delay!

**Comment by animatedmax** [comment]
This PR was not initially merged because cfdreddbot didn't see a CLA for
christianang, and we mistakenly overlooked the membership in the pivotal-cf
org. Sorry for the delay!

**Pull request merged**
