### PR TITLE
Add documents for customizing maniefsts for Azure with stubs

### PR DESCRIPTION
**Pull request by gossion**
Cloud Foundry is already supported in Azure for a while, we would like to add a document for Azure as other clouds about `how to generate/customize a manifest`. Several people had asked for this document.

This PR has
1.  A link to the document about initializing BOSH on Azure
2.  A guide about how to customize manifest on Azure using stubs.

### CODE REVIEW

**Comment by NingKuang** [comment]
Hi, @cf-gitbot , how often do you guys refresh the document? Is there anything we can do to make this quicker? We need to make it available to customers soon, thanks.

**Comment by sleslie23** [comment]
Hello @gossion @NingKuang Sorry for the delay in merging this PR. Since the Cloud Foundry Release Integration team does not test Cloud Foundry on Azure, we added a note at the top of each topic stating this.

Also, since this is not an environment that we test, can you help ensure that this content remains up-to-date? Since we do not have access to a CF environment on Azure, it will be very difficult for us to maintain this content.

**Comment by gossion** [comment]
Sure, @sleslie23. We will keep updating this document.

**Comment by sleslie23** [comment]
Thanks @gossion !!!

**Comment by NingKuang** [comment]
Hello @sleslie23 Thank you for merging the code.  We received some customer questions regarding this warning, it made people think that Azure is not a supported platform for Cloud Foundry. 
The  Azure Bosh CPI is formally merged into community code 1 years ago, and CF on Azure is officially supported by both the community and Microsoft, although this documentation not authored by the foundation, it is maintained and supported by Microsoft as a community effort,  is there anyway this warning can be removed? Thank you.

**Comment by jncd** [comment]
Hi @NingKuang I've reopened the original issue and have it reviewed by our Foundation experts here. Thanks!

**Comment by amitkgupta** [comment]
Hi @NingKuang 

Could you clarify what you mean "CF on Azure is officially supported by the community"?  By "community", do you mean Cloud Foundry Foundation?  The Cloud Foundry Foundation doesn't currently test CF on Azure, as the note under discussion mentions.

**Comment by animatedmax** [comment]
Hi @NingKuang

We have put the following notice in the Cloud Foundry on Microsoft Azure documentation:

"NOTE: Cloud Foundry on Microsoft Azure is supported by the community and Microsoft, but the Cloud Foundry Foundation does not currently test it."

If we are to reword or remove this message, we'd need to know what community is officially supporting it. The Cloud Foundry Foundation doesn't currently test CF on Azure, as the note under discussion mentions.

This issue has been open for more than 2 months now. Since we have not heard anything about it for the last 6 weeks, if we don't hear anything else within the next few days would like to close it.

Thanks much.

**Pull request merged**
